# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12464fdf8f8418b5da250ebb11b3a970160846280011931fdf58d98bf812e37792a5926c65c129d1896a44128c76d81fbf09fba17b0439102345b040c30c1e1f

test:
  secret_key_base: c5df9e20129c4720508c7b70358ea775e743877e2acdfea2bd1d8e632f9c6124c78c86db893442703e0c56ef89485182111106bf67ddafbb4a5c3221a6682b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
